import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/page";
import Footer from "./components/footer/page";
import { ThemeContext, ThemeProvider } from "./Context/themecontext";

export const metadata: Metadata = {
  title: "CP 05",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /** Implementa o ThemeProvider que guarda a informação do Themecontext para todas as páginas (Children)*/
    <html lang="en">
      <body>
      <ThemeProvider>
          <Header />
            {children}
          <Footer />
          </ThemeProvider>
      </body>
    </html>
  );
}
